version: '2'

services:
  traefik:
    image: traefik:1.4
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dataVolumes/traefik/traefik.toml:/traefik.toml
      - /dataVolumes/traefik/acme:/acme
      - /dataVolumes/traefik/logs:/logs
    networks:
      - traefik_default

 provisium:
    image: esiplab/provisium:0.0.8
    labels:
      - "traefik.backend=provisium"
      - "traefik.frontend.rule=Host:provisium.io"
    networks:
      - traefik_default

  provohash:
    image: esiplab/provohash:0.0.3
    labels:
      - "traefik.backend=provohash"
      - "traefik.frontend.rule=Host:provohash.xyz"
    networks:
      - traefik_default

  db:
    image: nawer/blazegraph
    environment:
      JAVA_XMS: 512m
      JAVA_XMX: 1g
    volumes:
      - /var/blazegraph:/var/lib/blazegraph
    ports:
      - "9999:9999"
    networks:
      - traefik_default

networks:
  traefik_default:
