version: '2'

services:
  traefik:
    image: traefik:1.4
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
        #      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/fils/Data/Provisium/traefik/traefik.toml:/traefik.toml
      - /home/fils/Data/Provisium/traefik/logs:/logs
    networks:
      - traefik_default

  provisium:
    image: esiplab/provisium:0.1.1
    command: /webapp
    labels:
      - "traefik.backend=provisium"
        #- "traefik.frontend.rule=Host:provisium.io"
      - "traefik.frontend.rule=Host:machine.dev"
    networks:
      - traefik_default

  provohash:
    image: esiplab/provohash:0.1.1
    labels:
      - "traefik.backend=provohash"
        #- "traefik.frontend.rule=Host:provohash.xyz"
      - "traefik.frontend.rule=Host:hash.machine.dev"
    networks:
      - traefik_default

        #  db:
        #    image: nawer/blazegraph
        #    environment:
        #      JAVA_XMS: 512m
        #      JAVA_XMX: 1g
        #    volumes:
        #      - /home/fils/Data/Provisium/:/var/lib/blazegraph
        #    ports:
        #      - "9999:9999"
        #    networks:
        #      - traefik_default

networks:
  traefik_default:
